EXTERN_C_START

NTSTATUS IVSHMEMQueueInitialize(_In_ WDFDEVICE Device);

EVT_WDF_IO_QUEUE_IO_DEVICE_CONTROL IVSHMEMEvtIoDeviceControl;
EVT_WDF_IO_QUEUE_IO_STOP           IVSHMEMEvtIoStop;
EVT_WDF_FILE_CLEANUP               IVSHMEMEvtDeviceFileCleanup;

EXTERN_C_END
