// For the concept of notify object see
// https://docs.microsoft.com/en-us/windows-hardware/drivers/network/notify-object-diagram

#include <netcfgn.idl>

[
    uuid(05539BEB-A85E-4639-AF27-7F5663840DE6),
    version(1.0),
    helpstring("NetKVM SR-IOV Notify Object 1.0 Type Library")
]
library NetKVMNotifyLib
{
    [
        uuid(F69513F1-8E1A-4F35-82D9-046406970E6D),
        helpstring("NetKVM SR-IOV Notify Class")
    ]
    coclass CNotifyObject
    {
        interface INetCfgComponentControl;
        interface INetCfgComponentSetup;
        interface INetCfgComponentNotifyBinding;
        interface INetCfgComponentNotifyGlobal;
    };
};
