#include <initguid.h>

DEFINE_GUID (GUID_DEVINTERFACE_VIOIVSHMEM,
    0xdf576976,0x569d,0x4672,0x95,0xa0,0xf5,0x7e,0x4e,0xa0,0xb2,0x10);
// {df576976-569d-4672-95a0-f57e4ea0b210}

typedef struct VIOIVSHMEM_MMAP
{
	UINT64 size;    // the size of the memory region
	PVOID  ptr;     // pointer to the memory region
	UINT16 vectors; // the number of vectors available
}
VIOIVSHMEM_MMAP, *PVIOIVSHMEM_MMAP;

typedef struct VIOIVSHMEM_RING
{
	UINT16 peerID;  // the id of the peer to ring
	UINT16 vector;  // the doorbell to ring
}
VIOIVSHMEM_RING, *PVIOIVSHMEM_RING;

#define IOCTL_VIOIVSHMEM_REQUEST_SIZE  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIOIVSHMEM_REQUEST_MMAP  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIOIVSHMEM_RELEASE_MMAP  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIOIVSHMEM_RING_DOORBELL CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)